### ISSUE TITLE
Make email share content more customisable

### ISSUE THREAD

**Issue by lozcalver** [jonom/silverstripe-share-care#5]
Currently to change the `Thought you might like this` / `Thought of you when I found this:` messages you need to create your own `$EmailShareLink` method on each page/DataObject.

Perhaps a better way of doing this is with i18n? Might also make localisation easier:

``` yml
en_GB:
  ShareCare:
    EMAILSUBECT: 'Thought you might like this'
    EMAILCONTENT: 'Thought of you when I found this: {link}'
```

``` php
$subject = urlencode(_t('ShareCare.EMAILSUBJECT', 'Thought you might like this'));
$body = urlencode(_t('ShareCare.EMAILCONTENT', 'Thought of you when I found this: {link}', array('link' => $pageURL)));
```

The `ShareCare.cms_message` config value could also be replaced with a boolean to enable/disable, and an `_t()` call to allow devs to customise the actual message
